### ISSUE TITLE
KeePass 2.45

### ISSUE THREAD

**Issue by jrsmile** [extide/MicrosoftKeyImporterPlugin#1]
Hi, any chance you could upgrade the dll to KeePass 2.45 ?

Would be great.

**Comment by extide** [comment]
I just tested it, and it does seem to work fine as-is but I will go ahead and rebuild it within the next few days against the 2.45 includes.

Thanks for the feedback!

**Comment by extide** [comment]
Updated, see https://github.com/extide/MicrosoftKeyImporterPlugin/releases/tag/1.0.3
